services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: camagru_frontend
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - uploads:/var/www/html/uploads:rw
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: camagru_backend
    env_file:
      - .env
    volumes:
      - uploads:/var/www/html/uploads:rw
    depends_on:
      - mariadb
    networks:
      - app_network

  # Database: MariaDB
  mariadb:
    image: mariadb:latest
    container_name: camagru_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app_network

  adminer:
    image: adminer
    container_name: camagru_dbclient
    ports:
      - "8080:8080"
    networks:
      - app_network


volumes:
  db_data:
    driver: local
  uploads:
    driver: local

networks:
  app_network:
    driver: bridge
